Repository atlas-outreach-data-tools/notebooks-collection-opendata, pull requests merged in 2024-10, with the labels that each got.

#57 Updating broken notebooks
  .github/workflows/docker_push.yml
  13-TeV-examples/uproot_python/CoffeaHZZAnalysis.ipynb
  13-TeV-examples/uproot_python/Dark_Matter_Machine_Learning.ipynb
  13-TeV-examples/uproot_python/Find_the_Z.ipynb
  13-TeV-examples/uproot_python/GravitonAnalysis.ipynb
  13-TeV-examples/uproot_python/HZZ_BDT_demo.ipynb
  13-TeV-examples/uproot_python/HZZ_NeuralNet_demo.ipynb
  13-TeV-examples/uproot_python/learning_rate_demo.ipynb
  13-TeV-examples/uproot_python/ttZ_ML_from_csv.ipynb
  13-TeV-examples/uproot_python/ttZ_ML_from_root.ipynb
  binder/environment.yml
Labels: enhancement, automation

#48 Added the ttbar analysis
  13-TeV-examples/uproot_python/ttbar_analysis.ipynb
Labels: documentation, enhancement, education release

#62 Example JSONs for phoenix
  for-research/phoenix/examples/ZZZ_4l2v.json
  for-research/phoenix/examples/Zprime_ee.json
  for-research/phoenix/examples/Zprime_mumu.json
  for-research/phoenix/examples/Zprime_munu.json
  for-research/phoenix/examples/jet_yyy.json
  for-research/phoenix/examples/jetjet_JZ10.json
  for-research/phoenix/examples/tH_ZZ4l.json
  for-research/phoenix/examples/top_3top.json
  for-research/phoenix/examples/ttH_ZZ4l.json
  for-research/phoenix/examples/ttbar_nonallhad.json
Labels: enhancement
