Repository atlas-outreach-data-tools/notebooks-collection-opendata, pull requests merged in 2024-08, with the labels that each got.

#46 Improvement of the Higgs to yy notebook
  13-TeV-examples/uproot_python/HyyAnalysisNew.ipynb
  13-TeV-examples/uproot_python/images/ImagesHiggs/VBFH.png
  13-TeV-examples/uproot_python/images/ImagesHiggs/WH.png
  13-TeV-examples/uproot_python/images/ImagesHiggs/ggH.png
  13-TeV-examples/uproot_python/images/ImagesHiggs/ttbarfusion.png
Labels: documentation, enhancement, education release

#38 Adding notebooks automated checks
  .github/workflows/docker_push.yml
  .github/workflows/notebooks-runner-autocheck.yml
  Dockerfile
Labels: documentation, enhancement, automation

#51 Adding single-check
  .github/workflows/notebooks-runner-autocheck.yml
  .github/workflows/single-notebook-check.yml
Labels: enhancement, automation
